### ISSUE TITLE
Flexibility in FastAPI versioning

### ISSUE THREAD

**Issue by timok19** [sijokun/async-fastapi-jwt-auth#17]
Hello @sijokun  ! I like your solution for JWT Token Authentication. I just wanted to ask if it is possible to make this library a bit flexible in versions of dependencies, such as FastAPI. It's quite complicated to install some dependencies due to it's versioning (e.g. poetry package manager is kinda annoying and it does not allow me to install the library).

Considering to make it flexible in a way that will allow to install on older versions of FastAPI, for example from 0.109.0.

Thank you and I hope it wouldn't make any problems.

**Comment by sijokun** [comment]
Sounds really good! You can make a PR and I will merge it.

**Comment by timok19** [comment]
I made a PR :+1:

**Comment by sijokun** [comment]
> I've made a PR

Merged! v0.6.5 will be published in a few minutes. Thank you!

**Comment by timok19** [comment]
> > I've made a PR
> 
> Merged! v0.6.5 will be published in a few minutes. Thank you!

I also thank you!
