### ISSUE TITLE
Use more well-known jwt package

### ISSUE THREAD

**Issue by BabakAmini** [sijokun/async-fastapi-jwt-auth#19]
@sijokun thanks for maintaining this repo. I'm aware that this is an async version of the original repository, and you might not be keen to modify some basic dependencies. But I hope you use more well-known packages like Autlib, which are [JWT-verified](https://jwt.io/libraries?language=Python), in favor of the `jwt` package used by the original repository. `jwt` does not seem to be maintained anymore, and this could pose security problems.

**Comment by sijokun** [comment]
You can create a pull request and I will merge it. Unfortunately I don't have time now to rewrite this project.

**Comment by sijokun** [comment]
Pyjwt is verified and is maintained, so there is no point in changing it
