### ISSUE TITLE
object bool can't be used in 'await' expression in Authorize.jwt_refresh_token_required()

### ISSUE THREAD

**Issue by dasunprem** [sijokun/async-fastapi-jwt-auth#3]
Hi
I get the error `object bool can't be used in 'await' expression` when I use ` await Authorize.jwt_refresh_token_required()`
I'm using Python 3.11.2 and async-fastapi-jwt-auth 0.5.1

if i remove the await expression then the exception is gone but the warning on the console will be shown ` RuntimeWarning: coroutine 'AuthJWT.jwt_refresh_token_required' was never awaited Authorize.jwt_refresh_token_required()`

I checked to update async-fastapi-jwt-auth 0.5.2 but pypi show 0.5.1

**Comment by sarthak7gupta** [comment]
Happened to me as well. Turn out my token_in_denylist_loader function was a sync function. made it async and it worked. [auth_jwt.py # #](https://github.com/sijokun/async-fastapi-jwt-auth/blob/1c077c861b8b796f2833bef9040599097c6bf9ec/async_fastapi_jwt_auth/auth_jwt.py#L244) needs this function to be async.
